HW15 improvements

diff --git a/hw12_13_14_15_calendar/Makefile b/hw12_13_14_15_calendar/Makefile
--- a/hw12_13_14_15_calendar/Makefile
+++ b/hw12_13_14_15_calendar/Makefile
@@ -57,6 +57,14 @@ down:
 	docker compose -f deployments/docker-compose.yaml down
 
 integration-tests:
-	docker compose -f deployments/integration-tests.yaml up integration_tests
+	@if docker compose -f deployments/integration-tests.yaml up --exit-code-from integration_tests; then \
+  		echo "Integration tests passed"; \
+  		docker compose -f deployments/integration-tests.yaml down; \
+  		exit 0; \
+	else \
+		echo "Integration tests failed"; \
+		docker compose -f deployments/integration-tests.yaml down; \
+		exit 1; \
+	fi
 
 .PHONY: build run build-img run-img version test lint up up-build down integration-tests
